#server:
#    port: 8085

spring:
    application:
        name: ezmpro
    jackson:
        date-format: "yyyy-MM-dd HH:mm:ss"
        time-zone: "GMT+8"
        joda-date-time-format: "yyyy-MM-dd HH:mm:ss"
        default-property-inclusion: always
    datasource:
        oracle:
            name: oracle
            jdbc-url: jdbc:oracle:thin:@16.186.72.139:1521:PPMSH16
            username: REFACTOR_960_YX1
            password: REFACTOR_960_YX1
            #            type: com.alibaba.druid.pool.DruidDataSource
            driver-class-name: oracle.jdbc.OracleDriver
        postgresql:
            name: postgresql
            jdbc-url: jdbc:postgresql://192.168.57.10:5432/ppm_master
            username: postgres
            password: postgres
#            type: com.alibaba.druid.pool.DruidDataSource
            driver-class-name: org.postgresql.Driver
#        dynamic:
#            druid:
#                initial-size: 0
#                max-active: 8
#                min-idle: 2
#                max-wait: -1
#                min-evictable-idle-time-millis: 30000
#                max-evictable-idle-time-millis: 30000
#                time-between-eviction-runs-millis: 0
#                validation-query: select 1
#                validation-query-timeout: -1
#                test-on-borrow: false
#                test-on-return: false
#                test-while-idle: true
#                pool-prepared-statements: true
#                filters: stat,wall
#                share-prepared-statements: true
#            primary: postgresql
#            datasource:
##                oracle:
##                    name: oracle
##                    url: jdbc:mysql://localhost:3306/ezmpro?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
##                    username: root
##                    password: mysql
##                    type: com.alibaba.druid.pool.DruidDataSource
##                    driver-class-name: com.mysql.jdbc.Driver
#                postgresql:
#                    name: postgresql
#                    url: jdbc:postgresql://192.168.57.10:3306/ppm_master
#                    username: postgres
#                    password: postgres
#                    type: com.alibaba.druid.pool.DruidDataSource
#                    driver-class-name: org.postgresql.Driver
    session:
        store-type: redis
        timeout: 7200
    cache:
        type: redis 

mybatis-plus:
    # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
    # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
    mapper-locations: classpath:mapper/*/*.xml
    #实体扫描，多个package用逗号或者分号分隔
    typeAliasesPackage: com.ppmbest.ezmpro.*.model
    global-config:
        #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
        id-type: 0
        #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
        field-strategy: 1
        #驼峰下划线转换
        #db-column-underline: true
        #刷新mapper 调试神器
        #refresh-mapper: true
        #数据库大写下划线转换
        #capital-mode: true
        # Sequence序列接口实现类配置
        #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
        #逻辑删除配置（下面3个配置）
        #logic-delete-value: 1
        #logic-not-delete-value: 0
        #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
        #自定义填充策略接口实现
        #meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
    configuration:
        map-underscore-to-camel-case: true
        cache-enabled: false
        #配置JdbcTypeForNull
        jdbc-type-for-null: 'null'
        call-setters-on-nulls: true
        #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


